# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: llion@student.42mulhouse.fr </var/spool/m  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/07/21 18:56:53 by llion@student     #+#    #+#              #
#    Updated: 2023/07/21 18:57:58 by llion@student    ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:latest

RUN useradd -u 1111 xavki # existe
RUN useradd -u 1113 xavki3 # n'existe pas
